### ISSUE TITLE
9️⃣ Week 9 개발 내용

### ISSUE THREAD

**Issue by ChanoPark** [ChanoPark/Beitool#3]
#### 🔥ToDo-List , 재고관리 게시판 개발
---

1️⃣ ToDo-List(DTYPE: Todo)
- [x] 도메인 작성
- [x] 할 일 작성 - 사장 권한 必
- [x] 조회 - 직원(자신에게 할당된 할 일 확인)
- [x] 해당 업무 완료 유무 체크  

~~할 일 삭제 - 사장 권한 必~~  

- [x] 할 일 수정
- [x] 사업장 회원 목록 반환

2️⃣ 재고관리(DTYPE: Stock)
- [x] 도메인 작성
- [x] 재고 관리 게시글 작성
- [x] 파일 업로드
- [x] 재고 관리 게시글 삭제
- [x] 재고 관리 게시글 수정

**Comment by ChanoPark** [comment]
ToDoList의 삭제는 따로 구현할 필요가 없다.

**Comment by ChanoPark** [comment]
- [x] 게시글 삭제시 본인 확인 절차 필요
- [x] 게시글 10개씩 페이징 필요

**Comment by ChanoPark** [comment]
- [x] 페이징 역순으로 되는 문제 해결
- [x] 총 페이지 수(totalPage)를 배열로 전달 (프론트 요청)
총 페이지가 4면 [1,2,3,4]와 같은 형태로 전달

**Comment by ChanoPark** [comment]
사진을 EC2 서버에 저장하면 비효율적이기 때문에(비용), AWS S3에 저장한다.

**Comment by ChanoPark** [comment]
- [x] 재고관리 상세 조회 시, 파일이름도 함께 Response해줘야 한다.
